/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.projetoSistemaMedico.view;

/**
 *
 * @author vanessalagomachado
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        miPacientes = new javax.swing.JMenuItem();
        miMedicos = new javax.swing.JMenuItem();
        mimedicamentos = new javax.swing.JMenuItem();
        menuReceitas = new javax.swing.JMenu();
        miReceituarios = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        miPacientes.setText("Pacientes");
        miPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacientesActionPerformed(evt);
            }
        });
        menuCadastro.add(miPacientes);

        miMedicos.setText("Medicos");
        miMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMedicosActionPerformed(evt);
            }
        });
        menuCadastro.add(miMedicos);

        mimedicamentos.setText("Medicamentos");
        mimedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimedicamentosActionPerformed(evt);
            }
        });
        menuCadastro.add(mimedicamentos);

        jMenuBar2.add(menuCadastro);

        menuReceitas.setText("Receitas");

        miReceituarios.setText("Receituarios");
        miReceituarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReceituariosActionPerformed(evt);
            }
        });
        menuReceitas.add(miReceituarios);

        jMenuBar2.add(menuReceitas);

        menuAjuda.setText("Ajuda");

        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(miSobre);

        jMenuBar2.add(menuAjuda);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mimedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimedicamentosActionPerformed
        // TODO add your handling code here:
        TelaMedicamentos telaMedicamentos = new TelaMedicamentos();
        telaMedicamentos.setVisible(true);
    }//GEN-LAST:event_mimedicamentosActionPerformed

    private void miReceituariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReceituariosActionPerformed
        // TODO add your handling code here:
        TelaReceituarios telaReceitas = new TelaReceituarios();
        telaReceitas.setVisible(true);
    }//GEN-LAST:event_miReceituariosActionPerformed

    private void miPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacientesActionPerformed
        // TODO add your handling code here:
        TelaPacientes telaPaciente = new TelaPacientes();
        telaPaciente.setVisible(true);
    }//GEN-LAST:event_miPacientesActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        // TODO add your handling code here:
        TelaSobre telaSobre = new TelaSobre(this, rootPaneCheckingEnabled);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_miSobreActionPerformed

    private void miMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMedicosActionPerformed
        // TODO add your handling code here:
        TelaMedicos telaMedicos = new TelaMedicos();
        telaMedicos.setVisible(true);
    }//GEN-LAST:event_miMedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuReceitas;
    private javax.swing.JMenuItem miMedicos;
    private javax.swing.JMenuItem miPacientes;
    private javax.swing.JMenuItem miReceituarios;
    private javax.swing.JMenuItem miSobre;
    private javax.swing.JMenuItem mimedicamentos;
    // End of variables declaration//GEN-END:variables
}
